### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by 12089897411** [gmu-swe/phosphor#181] opened 2022-08-31 06:35 UTC
Hi,
When I execute  "java -jar Phosphor-0.1.0-SNAPSHOT.jar --java8  web.zip test", it like this.

Data flow tracking: enabled
Control flow tracking: disabled
Branch not taken: enabled
Processed: 1000
Processed: 2001
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Saving module-info to debug-preinst/
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:325)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
method so far:
Processed: 3000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Saving module-info to debug-preinst/
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:325)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
method so far:
Processed: 4000
Processed: 5000
Processed: 6000
Processed: 7000
Processed: 8000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Saving module-info to debug-preinst/
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:325)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
method so far:
Processed: 9000
Processed: 10000
Processed: 11000
Processed: 12000
Processed: 13000
Processed: 14000
Processed: 15000
Processed: 16000
Processed: 17000
Processed: 18000
Processed: 19000
Processed: 20000
Processed: 21000
Processed: 22000
Processed: 23000
Exception occurred while instrumenting groovyjarjarantlr4/v4/unicode/UnicodeData:
edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodTooLargeException: Method too large: groovyjarjarantlr4/v4/unicode/UnicodeData.addPropertyAliases (Ledu/columbia/cs/psl/phosphor/runtime/PhosphorStackFrame;)V
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:489)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:274)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:318)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Saving groovyjarjarantlr4/v4/unicode/UnicodeData to debug-preinst/
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Saving module-info to debug-preinst/
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:325)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
method so far:
Processed: 24000
Processed: 25000
Processed: 26000
Processed: 27000
Processed: 28000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Saving module-info to debug-preinst/
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:325)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Saving module-info to debug-preinst/
java.lang.NullPointerException
        at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visit(TaintTrackingClassVisitor.java:135)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.OurSerialVersionUIDAdder.visit(OurSerialVersionUIDAdder.java:211)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:273)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.instrumentWithRetry(PreMain.java:325)
        at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:177)
        at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:146)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:434)
        at edu.columbia.cs.psl.phosphor.Instrumenter$3.call(Instrumenter.java:429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
method so far:
Processed: 29000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Processed: 30000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Processed: 31000
Processed: 32000
Processed: 33000
Processed: 34000
Processed: 35000
Processed: 36000
Processed: 37000
Processed: 38000
Processed: 39000
Processed: 40000
Processed: 41000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Processed: 42000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Processed: 43000
Processed: 44000
Processed: 45000
Processed: 46000
Processed: 47000
Processed: 48000
Processed: 49000
Processed: 50000
Processed: 51000
Processed: 52000
Processed: 53000
Processed: 54000
Processed: 55000
Processed: 56000
Processed: 57000
Processed: 58000
Processed: 59000
Processed: 60000
Processed: 61000
Processed: 62000
Processed: 63000
Processed: 64000
Processed: 65000
Processed: 66000
Processed: 67000
Processed: 68000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Processed: 69000
Processed: 70000
Processed: 71000
Processed: 72000
Processed: 73000
Processed: 74000
Processed: 75000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Processed: 76000
Processed: 77000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Processed: 78000
Exception occurred while instrumenting module-info:
java.lang.NullPointerException
Saving module-info to debug-preinst/
java.lang.NullPointerException
method so far:
Done after 76232 ms

Has it finished running? And what result is it

**Comment by jon-bell** [comment] 2022-08-31 13:39
It looks like it finished with some errors. Depending on where the errors were, running your application may or may not work. The current `master` branch is not super stable yet: it contains a major refactoring designed to improve functionality on newer versions of Java and more complex code generation. You might also try with the `phosphor-0.0.5-dev` branch, which contains the last commit before this refactoring.

Please note that this is an 8-year-old research project, and while we strive to continue to maintain it, we are currently somewhat limited in terms of development time. Resolving instrumentation errors like the ones that you pasted above is certainly possible (particularly given the major refactoring that I recently applied), but given my limited availability, it would be extremely useful if you could provide a minimal code example that triggers the error (ideally as a test case, as a pull request) - this would allow me to focus my time on fixing the bug that you have encountered, rather than on reproducing it.

**Comment by jon-bell** [comment] 2022-09-01 01:45
In general: yes, this tool supports java web projects. However: I am aware that some researchers have recently tried to use Phosphor with some spring-boot applications and experienced difficulties with applying our tool out-of-the-box. We are working on improving its compatibility. With that said: given the limited information that you have provided, I am not able to say whether or not Phosphor will work with your application.

**Comment by 12089897411** [comment] 2022-09-21 05:58
Hi @jon-bell 
Yes,I tried to use Phosphor with some spring-boot applications and experienced difficulties with applying our tool out-of-the-box.
It occurs with this error. Does this issue occur with all spring-boot applications?

**Comment by 12089897411** [comment] 2022-09-29 08:00
[demo-0.0.1-SNAPSHOT.zip](https://github.com/gmu-swe/phosphor/files/9672389/demo-0.0.1-SNAPSHOT.zip)
Hi,@jon-bell
This is my project!

**Comment by 12089897411** [comment] 2022-09-30 03:33
![image](https://user-images.githubusercontent.com/108512675/193184329-6883d3f9-83d0-4a09-b933-751e272171c9.png)

**Comment by jon-bell** [comment] 2022-10-10 19:18
I am pleased to report that the current revision of Phosphor does work with your app. I also saw the same NullPointerException's printed out during instrumentation, but then it ran fine afterwards. I can not see the full command that you are using to run it, but it looks likely incorrect. Here is the command that I used (in the base directory of this repository):

```
$ java -jar Phosphor/target/Phosphor-0.1.0-SNAPSHOT.jar spring-boot-example/demo-0.0.1-SNAPSHOT.jar spring-boot-example-inst
$ ./integration-tests/target/jvm-inst-data/bin/java -javaagent:phosphor-jigsaw-javaagent/target/phosphor-jigsaw-javaagent-0.1.0-SNAPSHOT.jar -jar spring-boot-example-inst/demo-0.0.1-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.2.RELEASE)

2022-10-10 15:16:06.549  INFO 14509 --- [           main] com.zbw.DemoApplication                  : Starting DemoApplication v0.0.1-SNAPSHOT on FACC02D63A5MD6T.localdomain with PID 14509 (/Users/jon/Documents/NEU/Projects/phosphor/spring-boot-example-inst/demo-0.0.1-SNAPSHOT.jar started by jon in /Users/jon/Documents/NEU/Projects/phosphor)
2022-10-10 15:16:06.561  INFO 14509 --- [           main] com.zbw.DemoApplication                  : No active profile set, falling back to default profiles: default
2022-10-10 15:16:12.830  INFO 14509 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 80 (http)
2022-10-10 15:16:12.878  INFO 14509 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-10-10 15:16:12.879  INFO 14509 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.37]
2022-10-10 15:16:13.088  INFO 14509 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-10-10 15:16:13.089  INFO 14509 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6096 ms
2022-10-10 15:16:16.545  INFO 14509 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2022-10-10 15:16:16.950  INFO 14509 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2022-10-10 15:16:18.281  INFO 14509 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 80 (http) with context path ''
2022-10-10 15:16:18.343  INFO 14509 --- [           main] com.zbw.DemoApplication                  : Started DemoApplication in 14.4 seconds (JVM running for 17.69)
2022-10-10 15:16:27.328  INFO 14509 --- [p-nio-80-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-10-10 15:16:27.329  INFO 14509 --- [p-nio-80-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-10-10 15:16:27.352  INFO 14509 --- [p-nio-80-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 23 ms
```

I will take a look at the NPE (although again, it does not appear to impact the app running).

**Comment by jon-bell** [comment] 2022-10-10 19:29
NPE fixed in 4d2eb3dc6d684f5989016bcf179759d2e11fa7ef . Please note in my above example running your demo app, for JVM 9+ support you'll need to use the jigsaw javaagent, and there is no need to specify an Xbootclasspath/a, because we pack Phosphor into the JVM now.

**Closed by jon-bell** 2022-10-10 19:29 UTC

**Comment by 12089897411** [comment] 2022-10-12 08:51
Thanks
But when I re-downloaded the project and rebuilt it, Maven reported an error.
It cannot download  'edu.gmu.swe.phosphor:phosphor-instrument-maven-plugin:0.1.0-SNAPSHOT'

**Comment by jon-bell** [comment] 2022-10-12 12:20
I understand that you have this other problem, too - you opened the other ticket, #180 with this other problem, right? Would you please follow along with my requests for more information from you there (~2 weeks ago)?  It would be helpful to hear more information about exactly what you are running (the environment and the command) and what you are seeing. Please note that I am still seeing passing behavior on mvn install in our CI workflow - https://github.com/gmu-swe/phosphor/actions/runs/2911505293
